# Generated by Django 4.0.6 on 2022-09-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0002_remove_emailaccount_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='username',
        ),
    ]
