# Generated by Django 4.0.6 on 2022-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0003_remove_emailaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
