# Generated by Django 4.0.6 on 2022-09-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0005_alter_emailaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
