# Generated by Django 4.0.6 on 2022-09-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0006_emailaccount_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
