# Generated by Django 4.0.6 on 2022-09-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0007_remove_emailaccount_is_verified_emailaccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
