# Generated by Django 4.0.6 on 2022-09-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(choices=[('اول ابتدائي', 'اول ابتدائي'), ('ثاني ابتدائي', 'ثاني ابتدائي'), ('ثالث ابتدائي', 'ثالث ابتدائي'), ('رابع ابتدائي', 'رابع ابتدئي'), ('خامس ابتدائي', 'خامس ابتدائي'), ('سادس ابتدائي', 'سادس ابتدائي'), ('اول متوسط', 'اول متوسط'), ('ثاني متوسط', 'ثاني متوسط'), ('ثالث متوسط', 'ثالث متوسط'), ('رابع اعدادي', 'رابع اعدادي'), ('خامس اعدادي', 'خامس اعدادي'), ('سادس اعدادي', 'سادس اعدادي')], max_length=255)),
                ('type', models.CharField(choices=[('علمي', 'علمي'), ('ادبي', 'ادبي'), ('احيائي', 'احيائي'), ('تطبيقي', 'تطبيقي'), ('لا يوجد', 'لا يوجد')], default='لا يوجد', max_length=255)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'unique_together': {('stages', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_stage', to='Home.stage')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='UserScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score_points', models.IntegerField(default=0, editable=False)),
                ('total_right_choices', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_scoring', to='Home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0, editable=False)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_userquizzes', to='Home.chapters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_userquizzes', to='Home.subjects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_userquizzes', to='Home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('timer', models.CharField(choices=[('5', '5:00'), ('10', '10:00'), ('15', '15:00'), ('20', '20:00'), ('25', '25:00'), ('30', '30:00'), ('35', '35:00'), ('40', '40:00'), ('45', '45:00'), ('50', '50:00'), ('55', '55:00'), ('60', '60:00')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('q_num', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_chapter', to='Home.chapters')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_stage', to='Home.stage')),
                ('subject', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stage', chained_model_field='stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_subject', to='Home.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionBody', models.CharField(blank=True, max_length=255, null=True)),
                ('isProblem', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_quiz', to='Home.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_stage', to='Home.stage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceBody', models.CharField(blank=True, max_length=70, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_question', to='Home.question')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_subject', to='Home.subjects'),
        ),
    ]
