# Generated by Django 4.0.6 on 2022-09-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_quiz_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_chapter', to='Home.chapters'),
        ),
    ]
