# Generated by Django 4.0.6 on 2022-09-12 13:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_quiz_chapter_alter_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
