# Generated by Django 4.0.6 on 2022-09-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_subjects_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='color',
        ),
    ]
