# Generated by Django 4.0.6 on 2022-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_subjects_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='num',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
