# Generated by Django 4.0.6 on 2022-09-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_remove_userquizzes_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscoring',
            old_name='total_right_choices',
            new_name='total_right_points',
        ),
        migrations.RemoveField(
            model_name='userquizzes',
            name='quiz',
        ),
        migrations.AddField(
            model_name='userquizzes',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_userquizzes', to='Home.chapters'),
        ),
        migrations.AddField(
            model_name='userquizzes',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_userquizzes', to='Home.subjects'),
        ),
    ]
