# Generated by Django 4.0.6 on 2022-09-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_remove_userquizzes_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizzes',
            name='user_scoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userquizzes_userscoring', to='Home.userscoring'),
        ),
    ]
