# Generated by Django 4.0.6 on 2022-09-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_userquizzes_user_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscoring',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_scoring', to='Home.profile'),
        ),
    ]
