# Generated by Django 4.0.6 on 2022-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_choices_question_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('subject', 'chapter')},
        ),
    ]
