# Generated by Django 4.0.6 on 2022-09-15 23:49

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='subject', chained_model_field='subject', horizontal=True, to='Home.chapters', verbose_name='writer'),
        ),
    ]
