# Generated by Django 4.0.6 on 2022-09-16 02:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_remove_quiz_chapter_quiz_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_chapter', to='Home.chapters'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='subject', chained_model_field='subject', horizontal=True, to='Home.chapters', verbose_name='chapters'),
        ),
    ]
