# Generated by Django 4.0.6 on 2022-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='num',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
