# Generated by Django 4.0.6 on 2022-09-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_chapters_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('name', 'stage')},
        ),
    ]
